apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: hugo
  name: hugo-rolebinding
roleRef:
  kind: Role
  name: hugo-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hugo-service-account
  namespace: hugo

